// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// altrandomStrings
SEXP altrandomStrings(int N);
RcppExport SEXP _altstringisode_altrandomStrings(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(altrandomStrings(N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_altstringisode_altrandomStrings", (DL_FUNC) &_altstringisode_altrandomStrings, 1},
    {NULL, NULL, 0}
};

void init_stdvec_double(DllInfo* dll);
RcppExport void R_init_altstringisode(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    init_stdvec_double(dll);
}
